### ISSUE TITLE
Following links broken after backspace

### ISSUE THREAD

**Issue by treeman** [tbabej/taskwiki#116]
After restarting vim (I use neovim) I got a repeat of this behavior:

1. Press enter on a link to visit a new file.
2. Backspace goes back to the previous file.
3. Try to press enter again, but now you can't visit any link anymore. No error or reaction is visible.

By disabling taskwiki and only operating on vimwiki it works as expected.

**Comment by tbabej** [comment]
This works for me (neovim), so I'm not sure where your setup is different. I recorded a demo:

https://asciinema.org/a/dts3yqq2q7an90qatd2gg77zx

Note: I have neovim aliased to vim.

**Comment by tbabej** [comment]
So I guess the steps forward are:

1. Boil it down to the minimal example that does not work
2. Share it with us :)

**Comment by treeman** [comment]
Then it almost seems like a setup issue. I do get a strange error when I try to save a file with a task list in it:

```
Error detected while processing function provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tree/dotfiles/.nvim/plugged/taskwiki/taskwiki/errors.py", line 26, in wrapped_function
    original_function(*args, **kwargs)
  File "/home/tree/dotfiles/.nvim/plugged/taskwiki/taskwiki/main.py", line 57, in update_to_tw
    cache.buffer.push()
  File "/home/tree/dotfiles/.nvim/plugged/taskwiki/taskwiki/cache.py", line 23, in push
    util.get_buffer(self.buffer_number)[:] = self.data
  File "/usr/lib64/python3.5/site-packages/neovim/api/buffer.py", line 65, in __setitem__
    return self.request('buffer_set_lines', start, end, False, lines)
  File "/usr/lib64/python3.5/site-packages/neovim/api/common.py", line 44, in request
    return self._session.request(name, self, *args, **kwargs)
  File "/usr/lib64/python3.5/site-packages/neovim/api/nvim.py", line 131, in request
    res = self._session.request(name, *args, **kwargs)
"test.wiki" 3L, 18C [w]
Press ENTER or type command to continue   [link]]
```

It may be a silent error which breaks after I try to go back?

Here's some relevant setup info:

```
> python3 --version
Python 3.5.2

> pip3 show tasklib
Name: tasklib
Version: 1.0.0
Summary: Python Task Warrior library
Home-page: https://github.com/robgolding63/tasklib
Author: Rob Golding
Author-email: rob@robgolding.com
License: BSD
Location: /usr/lib64/python3.5/site-packages
Requires: six, pytz, tzlocal

> pip3 show neovim
Name: neovim
Version: 0.1.13
Summary: Python client to neovim
Home-page: http://github.com/neovim/python-client
Author: Thiago de Arruda
Author-email: tpadilha84@gmail.com
License: Apache
Location: /usr/lib64/python3.5/site-packages
Requires: msgpack-python, greenlet

> nvim --version
NVIM v0.2.0-396-ga265ff4
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/tree/slackware/src/neovim/build/config -I/home/tree/slackware/src/neovim/src -I/home/tree/slackware/src/neovim/.deps/usr/include -I/home/tree/slackware/src/neovim/.deps/usr/include -I/home/tree/slackware/src/neovim/.deps/usr/include -I/home/tree/slackware/src/neovim/.deps/usr/include -I/home/tree/slackware/src/neovim/.deps/usr/include -I/home/tree/slackware/src/neovim/.deps/usr/include -I/usr/include -I/home/tree/slackware/src/neovim/build/src/nvim/auto -I/home/tree/slackware/src/neovim/build/include
Compiled by tree@thewall

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```

Taskwiki should be updated:
```
> git log
commit 4b55082413867bc67003aa1bf0f968eaf62a2675
Author: Tomas Babej <tomasbabej@gmail.com>
Date:   Wed Jan 11 11:17:39 2017 +0100

    tests: Test proper precise detection of vimwiki links
```

**Comment by tbabej** [comment]
You're running a bit newer neovim than me (I'm using latest released 0.1.7, not the dev version). Otherwise we're even. Can you maybe try to downgrade to check if the problem is there?

Other thing is that the traceback is missing the last line. I think making it appear again with `:messages` should show everything.

**Comment by treeman** [comment]
Error seems to remain with the latest release as well.

```
> nvim --version
NVIM v0.1.7
Build type: Debug
```

Error copied from `:messages`, it does add the task to taskwarrior:

```
Error detected while processing function provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tree/dotfiles/.nvim/plugged/taskwiki/taskwiki/errors.py", line 26, in wrapped_function
    original_function(*args, **kwargs)
  File "/home/tree/dotfiles/.nvim/plugged/taskwiki/taskwiki/main.py", line 54, in update_to_tw
    cache.save_tasks()
  File "/home/tree/dotfiles/.nvim/plugged/taskwiki/taskwiki/cache.py", line 129, in save_tasks
    task.save_to_tw()
  File "/home/tree/dotfiles/.nvim/plugged/taskwiki/taskwiki/vwtask.py", line 262, in save_to_tw
    self.task.save()
  File "/usr/lib64/python3.5/site-packages/tasklib/task.py", line 405, in save
    self.backend.save_task(self)
  File "/usr/lib64/python3.5/site-packages/tasklib/backends.py", line 356, in save_task
    task.refresh(after_save=True)
  File "/usr/lib64/python3.5/site-packages/tasklib/task.py", line 436, in refresh
    self._load_data(new_data)
  File "/usr/lib64/python3.5/site-packages/tasklib/task.py", line 67, in _load_data
    self._original
"vimwiki/test.wiki" 3L, 20C [w]
Press ENTER or type command to continue
```

I'm worried the connection with python isn't setup right. Is there a way to test it out?

**Comment by treeman** [comment]
I tried `:CheckHealth` and got this:

```
## Python 2 provider
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.11
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.5.2
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13
```

And double checked `tasklib`:
```
> pip3 install --upgrade tasklib
Requirement already up-to-date: tasklib in /usr/lib64/python3.5/site-packages
Requirement already up-to-date: six>=1.4 in /usr/lib64/python3.5/site-packages (from tasklib)
Requirement already up-to-date: pytz in /usr/lib64/python3.5/site-packages (from tasklib)
Requirement already up-to-date: tzlocal in /usr/lib64/python3.5/site-packages (from tasklib)
```

But without any luck.

**Comment by tbabej** [comment]
No, this all seems good. Does taskwarrior itself work fine though? Things to try:

* Some simple CLI taskwarrior work
* Run tests from the tasklib suite

**Comment by tbabej** [comment]
* try to run open the file with regular vim, it shows the tracebacks better (neovim, it seems, always strips down the last line, which is annoying since it contains the actual error message)

**Comment by treeman** [comment]
120 of the 149 tests in tasklib seems to fail. [http://pastebin.com/d3GWDxwY](url)

I played around a bit with taskwarrior itself and it seems to work. I ran their unit tests and they all passed except the one checking the copyright for the current year.

This is the error I get with regular vim (although I think it uses python2 instead of python3 as neovim does).

```
Error detected while processing BufWrite Auto commands for "*.wiki":
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tree/dotfiles/.nvim/plugged/taskwiki/taskwiki/errors.py", line 26, in wrapped_function
    original_function(*args, **kwargs)
  File "/home/tree/dotfiles/.nvim/plugged/taskwiki/taskwiki/main.py", line 54, in update_to_tw
    cache.save_tasks()
  File "/home/tree/dotfiles/.nvim/plugged/taskwiki/taskwiki/cache.py", line 129, in save_tasks
    task.save_to_tw()
  File "/home/tree/dotfiles/.nvim/plugged/taskwiki/taskwiki/vwtask.py", line 262, in save_to_tw
    self.task.save()
  File "/usr/lib64/python2.7/site-packages/tasklib/task.py", line 405, in save
    self.backend.save_task(self)
  File "/usr/lib64/python2.7/site-packages/tasklib/backends.py", line 356, in save_task
    task.refresh(after_save=True)
  File "/usr/lib64/python2.7/site-packages/tasklib/task.py", line 436, in refresh
    self._load_data(new_data)
  File "/usr/lib64/python2.7/site-packages/tasklib/task.py", line 67, in _load_data
    self._original_data = copy.deepcopy(self._data)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.7/copy.py", line 328, in _reconstruct
    args = deepcopy(args, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 237, in _deepcopy_tuple
    y.append(deepcopy(a, memo))
  File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.7/copy.py", line 329, in _reconstruct
    y = callable(*args)
  File "/usr/lib64/python2.7/site-packages/pytz/__init__.py", line 287, in _p
    return unpickler(*args)
  File "/usr/lib64/python2.7/site-packages/pytz/tzinfo.py", line 526, in unpickler
    tz = pytz.timezone(zone)
  File "/usr/lib64/python2.7/site-packages/pytz/__init__.py", line 181, in timezone
    raise UnknownTimeZoneError(zone)
"test.wiki" 1L, 10C [w]
Press ENTER or type command to continue
```

This error message seems to be the same, or similar, as one in the tasklib test log.

**Comment by tbabej** [comment]
Okay, then we found the culprit. What is the output of

    >>> import tzlocal
    >>> tzlocal.get_localzone()

and what distro are you using?

**Comment by tbabej** [comment]
You might want to raise an issue over at `tzlocal`: https://github.com/regebro/tzlocal/

That said, exporting the following environment var in your .bashrc should fix this for you:

    export TZ="Europe/Stockholm"

**Comment by treeman** [comment]
Okay so setting `TZ` makes it so I can save the file on my first visit.


```
> echo $TZ

> python3
>>> import tzlocal
>>> tzlocal.get_localzone()
<DstTzInfo 'local' CET+1:00:00 STD>

> echo $TZ
Europe/Stockholm
> python3
>>> import tzlocal
>>> tzlocal.get_localzone()
<DstTzInfo 'Europe/Stockholm' SET+1:00:00 STD>
```

I'm still having the problem with following a link the second time after I've gone back. When I try to save the file at that time it doesn't work either and I get a new error:

Regular vim:
```
Error detected while processing BufWrite Auto commands for "*.wiki":                           
E315: ml_get: invalid lnum: 3
```

neovim (still cutoff...):
```
Traceback (most recent call last):                                                                        
  File "<string>", line 1, in <module>                                                                    
  File "/home/tree/dotfiles/.nvim/plugged/taskwiki/taskwiki/errors.py", line 26, in wrapped_function      
    original_function(*args, **kwargs)                                                                    
  File "/home/tree/dotfiles/.nvim/plugged/taskwiki/taskwiki/main.py", line 57, in update_to_tw            
    cache.buffer.push()                                                                                   
  File "/home/tree/dotfiles/.nvim/plugged/taskwiki/taskwiki/cache.py", line 23, in push                   
    util.get_buffer(self.buffer_number)[:] = self.data                                                    
  File "/usr/lib64/python3.5/site-packages/neovim/api/buffer.py", line 65, in __setitem__                 
    return self.request('buffer_set_lines', start, end, False, lines)                                     
  File "/usr/lib64/python3.5/site-packages/neovim/api/common.py", line 44, in request                     
    return self._session.request(name, self, *args, **kwargs)                                             
  File "/usr/lib64/python3.5/site-packages/neovim/api/nvim.py", line 131, in request                      
    res = self._session.request(name, *args, **kwargs)                                                    
  File "/usr/lib64/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 98, in requ
```

This time with `TZ` set up I get a pass on all tests in tasklib.

For reference I'm on Slackware.

**Comment by tbabej** [comment]
Okay, we will need exact content of those buffers, and also information about whether both of the files being switched exist and are already saved on the disk.

**Comment by treeman** [comment]
The repeat of the error:

1. Edit `test.wiki`
2. Make a link `[[link]]` and visit it.
3. Go back with backspace.
4. Now you cannot go back anymore.
    If you save it with the contents:
    ```
    * [ ] xyz
    ```
    Then you get the error on save if `test.wiki` was an existing file. If it's a nonexisting file it will not produce an error.

If I try to save `link.wiki` it works regardless of the file exists or not.

I don't know how to make neovim spit out the whole error log?

A curious thing:

If I save `link.wiki` as:

```
* [ ] abc
```

and then when I go back and try to visit `link` again a prompt at the bottom opens up describing the tasks inside link. If I close vim and open `test.wiki` again I can visit `link` again.

**Comment by tbabej** [comment]
Like this?

https://asciinema.org/a/61xxb8fje6psoobo7td8eaz9h

**Comment by treeman** [comment]
Tried out asciinema (cool tool):

https://asciinema.org/a/ah14nthjh9sqjl830sgfwcnfh

**Comment by tbabej** [comment]
Very interesting. So to recap, this does not happen with vim, only with neovim, right?

We need to extract that traceback. Things to try:

* does explicitly calling `:TaskwikiBufferSave` produce different (maybe full) traceback?
* maybe installing python client version from this pull request would help? https://github.com/neovim/python-client/pull/221

**Comment by treeman** [comment]
No I have problems wth vim as well, although the error message is slightly different.

No difference with `:TaskwikiBufferSave`, but I managed to get a longer trace with the pull request:

```
Traceback (most recent call last):                                                                                                                                        
  File "<string>", line 1, in <module>                                                                                                                                    
  File "/home/tree/dotfiles/.nvim/plugged/taskwiki/taskwiki/errors.py", line 26, in wrapped_function                                                                      
    original_function(*args, **kwargs)                                                                                                                                    
  File "/home/tree/dotfiles/.nvim/plugged/taskwiki/taskwiki/main.py", line 57, in update_to_tw                                                                            
    cache.buffer.push()                                                                                                                                                   
  File "/home/tree/dotfiles/.nvim/plugged/taskwiki/taskwiki/cache.py", line 23, in push                                                                                   
    util.get_buffer(self.buffer_number)[:] = self.data                                                                                                                    
  File "/usr/lib64/python3.5/site-packages/neovim/api/buffer.py", line 71, in __setitem__                                                                                 
    True, include_end, lines)                                                                                                                                             
  File "/usr/lib64/python3.5/site-packages/neovim/api/nvim.py", line 129, in request                                                                                      
    res = self._session.request(name, *args, **kwargs)                                                                                                                    
  File "/usr/lib64/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 98, in request                                                                            
    raise self.error_wrapper(err)                                                                                                                                         
neovim.api.nvim.NvimError: b'Vim:E315: ml_get: invalid lnum: 3'
```

This is the error using vim:

```
Error detected while processing BufWrite Auto commands for "*.wiki":
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tree/dotfiles/.nvim/plugged/taskwiki/taskwiki/errors.py", line 26, in wrapped_function
    original_function(*args, **kwargs)
  File "/home/tree/dotfiles/.nvim/plugged/taskwiki/taskwiki/main.py", line 57, in update_to_tw
    cache.buffer.push()
  File "/home/tree/dotfiles/.nvim/plugged/taskwiki/taskwiki/cache.py", line 23, in push
    util.get_buffer(self.buffer_number)[:] = self.data
vim.error: Vim:E315: ml_get: invalid lnum: 3
```

**Comment by canaaerus** [comment]
Ok, I have located the source of this bug.

The problem is, as I suspected from the reported behavior, that taskwiki does not correctly track the current buffer. This also explains some other non-reproducible errors I got.

To debug the issue I put `print(vim.current.buffer.number)` at the beginning of `main.py`. The following is what I observed:

*  `main.py:21` creates a global `TaskCache` object `cache`, that captures the current buffer number
* `main.py` is executed only when the wiki file is loaded in vim, but not when changing buffers.
* I have the `'hidden'` option set, making buffers remain loaded when switching between them.
* Thus buffer switches can not be noticed by the `cache`.
* The wrong buffer number is then used in the static methods, e.g. of `Mappings`.

So I guess you need to make some architectural changes...

**Comment by tbabej** [comment]
Thanks for the investigation!  We were actually able to trace it down with @treeman too, but I haven't fixed it since I was unable to reproduce it on my machine.

Turns out the `hidden` option is the culprit here: `echo &hidden` returns 0 on my setup, hence every buffer was being reloaded each time. I thought that was the behaviour everybody was getting - so I guess I also need to learn more about Vim :)

**Comment by canaaerus** [comment]
I just want to note that problems can occur even with `hidden` disabled. For example if you open have a split window (`CTRL-W v`) and open taskwiki files in both of them. Then taskwiki will think you are in the last-opened buffer, while you can freely move between the two (`CTRL-W h` and `CTRL-W l`).

**Comment by tbabej** [comment]
I think if we use `BufEnter` autocmd group to detect the jumps we should cover all these cases. Then it's a question of either reloading the cache each time or keeping a dictionary of caches, one for each buffer.

**Comment by leesio** [comment]
I'm having this exact issue and the description proposed by @canaaerus seems to hold true for me too. Knowing the cause is half the battle, right? :)

**Comment by tbabej** [comment]
Yes. Fixing the issue should not be hard, but I am currently quite busy to devote the necessary time to fix it. High level approach I would take is available though :)

**Comment by canaaerus** [comment]
So I guess this can be closed then.
